 import { aijob, database, project, uiux } from "../../assets";

export let companyDetails =[
  {
    image: 'https://cdn-icons-png.flaticon.com/512/2875/2875404.png',
    name : "Google LLC.",
    location : "Mountain View, CA, USA"
  },
  {
    image: 'https://cdn.iconscout.com/icon/premium/png-256-thumb/facebook-2752192-2285009.png?f=webp&w=256',
    name :  "Facebook",
    location : "Menlo Park, CA, USA"
  },
  {
    image: 'https://cdn.iconscout.com/icon/premium/png-512-thumb/youtube-3856171-3201504.png?f=webp&w=256',
    name :  "Youtube",
    location : "San Bruno, CA, USA"
  },
  // {
  //   image: uiux,
  //   name : "Google LLC."
  // },
  // {
  //   image: database,
  //   name :  "Facebook"
  // },
  // {
  //   image: uiux,
  //   name :  "Youtube"
  // },
]


 export const perPage =[
  {
    id: 1 ,
    item: "10 Per Page",
    val: 10
  },
  {
    id: 2 ,
    item: "20 Per Page",
    val: 20
  },
  {
    id: 3 ,
    item: "30 Per Page",
    val: 30
  },
  {
    id: 4 ,
    item: "40 Per Page",
    val: 40
  },
 ]
 export const shortBy =[
{
  id:1,
  item: "Short By (Default)"
},
{
  id:2,
  item: "Short By (Date)"
},
{
  id:3,
  item: "Short By (Salary)"
},
{
  id:4,
  item: "Short By (Remote)"
},
 ]


 export const cartData = [
    {
      id: "0",
      item: "Job Category",
    },
    {
      id : 1,
      item: "Art & Design",
    },
    {
      id : 2,
      item: "Health & Fitness",
    },
    {
      id : 3,
      item: "Finance & Business",
    },
    {
      id : 4,
      item: "Art & Music",
    },
    {
      id : 5,
      item: "Marketing",
    },
    {
      id : 6,
      item: "Teaching & Study",
    },
    {
      id : 7,
      item: "Photography",
    },
    {
      id : 8,
      item: "It Management",
    },
  ];
  export let companyData = [
    
      {
          "id": "LVcC6ATG9_UlY54vAAAAAA==",
          "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJpHPsPCtT7v0dsfLzY7WalItl5ZK269S36ESB&s=0",
          "name": "Amazon.com Services LLC",
          "position": "SDE-I",
          "location": "Seattle, WA, US",
          "date": "07/10/2024",
          "deadline": "Tue Feb 04 2025",
          "fullTime": true,
          "partTime": false,
          "contract": false,
          "remote": false,
          "onsite": true,
          "minPrice": "Dependent on the position offered, equity, sign-on payments, and other forms of compensation may be provided as part of a total compensation package, in addition to a full range of medical, financial, and/or other benefits",
          "maxPrice": "N/A",
          "per": "Month",
          "description": "• 1+ years of non-internship professional software development experience\n• Experience programming with at least one software programming language\n\nAmazon Prime’s Science organization leads the Research & Development towards innovation for Amazon Prime. Amazon Prime is the backbone of Amazon’s consumer business and aspires to be the world’s most engaging, satisfying, and loved membership program, driving growth and profitability. The program serves over 200 million members across 25 countries and is key to Amazon’s customer growth and engagement. Prime Science innovates in Artificial Intelligence and Economics, to develop algorithms and systems for automated marketing, personalization, targeting, and decisioning. Within the engineering group in Prime Science, we develop world class solutions to complex scientific and engineering problems at Amazon scale. You will work alongside world class scientists to build a suite of fully automated, scalable and robust products driven by the data systems you develop.\n\nHave you wondered how Amazon uses big data and science to inform big strategic decisions? Are you ready to take your career to new heights and make a profound impact at the intersection of science, technology and innovation? Do you want to work in a multi-disciplinary group of product managers, ML scientists, economists, finance analysts, data engineers and software engineers to build tools to help Amazon make science-driven decisions on how to make the Amazon Prime membership better for our customers? If your answer is yes, come join us as we work on this unique intersection of science, engineering and business.\n\nAs part of the engineering group of WW Prime Science organization we are responsible for building out infrastructure and application-level components for the Prime Econ products that inform strategic investment decisions in prime and its benefits and helping business determining the value each prime benefit brings to our customers. You will work closely with a team of structural and theoretical econometricians, applied and research scientists, and business and software development teams, along with Amazon Scholars (leading academic scientists from major universities). You will extensively collaborate with scientists in proposing and estimating novel statistical and econometric models at the scientific frontier of time series statistics, structural econometrics, and machine learning. You will directly inform large-scale strategic decisions about how to improve the Prime membership, in partnership with senior scientific and business leaders. You will enhance and optimize massively parallelized scientific computing paradigms, in partnership with our Scientists. This position is unique in its exposure to senior members of the Prime team and other Amazon business units. Our North star vision is to revolutionize scientific research by providing self-service tools that enable scientists, PMs, finance/business professionals to effortlessly run simulations or science applications with guardrails. We seek bold inventors to help us meet the challenges of this mandate.\n\nKey job responsibilities\nCollaborate with experienced cross-disciplinary Amazonians to conceive, design, and bring innovative products and services to market.\nDesign and build innovative technologies in a large distributed computing environment and help lead fundamental changes in the industry.\nCreate solutions to run predictions on distributed systems with exposure to innovative technologies at incredible scale and speed.\nBuild distributed storage, index, and query systems that are scalable, fault-tolerant, low cost, and easy to manage/use.\nDesign and code the right solutions starting with broadly defined problems.\nWork in an agile environment to deliver high-quality software\n• Bachelor's degree in computer science or equivalent\n\nAmazon is committed to a diverse and inclusive workplace. Amazon is an equal opportunity employer and does not discriminate on the basis of race, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other legally protected status. For individuals with disabilities who would like to request an accommodation, please visit https://www.amazon.jobs/en/disability/us.\n\nOur compensation reflects the cost of labor across several US geographic markets. The base pay for this position ranges from $99,500/year in our lowest geographic market up to $200,000/year in our highest geographic market. Pay is based on a number of factors including market location and may vary depending on job-related knowledge, skills, and experience. Amazon is a total compensation company. Dependent on the position offered, equity, sign-on payments, and other forms of compensation may be provided as part of a total compensation package, in addition to a full range of medical, financial, and/or other benefits. For more information, please visit https://www.aboutamazon.com/workplace/employee-benefits. This position will remain posted until filled. Applicants should apply via our internal or external career site.",
          "requirements": "1+ years of non-internship professional software development experience\nExperience programming with at least one software programming language\nBachelor's degree in computer science or equivalent",
          "responsibilities": "You will extensively collaborate with scientists in proposing and estimating novel statistical and econometric models at the scientific frontier of time series statistics, structural econometrics, and machine learning\nYou will directly inform large-scale strategic decisions about how to improve the Prime membership, in partnership with senior scientific and business leaders\nYou will enhance and optimize massively parallelized scientific computing paradigms, in partnership with our Scientists\nCreate solutions to run predictions on distributed systems with exposure to innovative technologies at incredible scale and speed\nBuild distributed storage, index, and query systems that are scalable, fault-tolerant, low cost, and easy to manage/use\nDesign and code the right solutions starting with broadly defined problems",
          "vacancy": 1,
          "apply_link": "https://www.indeed.com/viewjob?jk=f3d42d4ee1f1e2bf&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          "availability": "Hourly",
          "education": "Not Specified",
          "gender": "Not Specified",
          "age": "21+",
          "experience": "12 months",
          "language": "English"
      },
      {
        "id": "aq_UVIJZHbXfqmdyAAAAAA==",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdMVUNivMZMzOue48X2VFmMzfK9p4wP7dopSc6&s=0",
        "name": "Walmart",
        "position": "Software Engineer II",
        "location": "Bentonville, AR, US",
        "date": "03/10/2024",
        "deadline": "September 20, 2025",
        "fullTime": true,
        "partTime": false,
        "contract": false,
        "remote": false,
        "onsite": true,
        "minPrice": "Other great perks include a host of best-in-class benefits maternity and parental leave, PTO, health benefits, and much more",
        "maxPrice": "At Walmart, we offer competitive pay as well as performance-based bonus awards and other great benefits for a happier mind, body, and wallet",
        "per": "Month",
        "description": "Position Summary...\n\nWhat you'll do...\n\nAre you excited about building engaging user interfaces and contributing to innovative digital solutions? Do you have a passion for front-end development and want to grow your career while working on impactful projects? If so, you may be the ideal candidate for our Software Engineer II (Front-End Developer) position at Walmart Global Tech.\n\nAs a Software Engineer II in the Customer Trust Gateway organization, you will play a key role in designing and developing high-quality, user-centric web applications. You will be responsible for implementing dynamic and responsive interfaces using modern front-end technologies such as React, CSS, and JavaScript. This includes collaborating with UX/UI designers and backend engineers to create seamless and intuitive user experiences that support our customer trust and privacy initiatives.\n\nIn this role, you will leverage your front-end development skills to contribute to innovative solutions that align with our business objectives. You will have the opportunity to grow your expertise in technologies such as TypeScript and micro-frontend architecture while working on meaningful projects. Additionally, you will collaborate closely with your team to ensure that all front-end work is of high quality and adheres to best practices.\n\nAbout the Team:\n\nOur organization, i.e. Customer Trust and Digital Citizenship Tech, focuses on managing and delivering world-class products, driving policy compliance, creating partnerships, and developing pipelines and self-service tools. Responsible for Global Privacy Technology Product implementation(s) so that we can earn customers and associate trust.\n\nWhat You Will Do:\n\n· Design and build responsive, user-friendly web applications using React, CSS, and JavaScript. Ensure that interfaces are intuitive, performant, and meet the needs of our users.\n\n· Write clean, maintainable code with a focus on using TypeScript to enhance reliability and scalability. Conduct unit testing to ensure the functionality and stability of your code.\n\n· Work closely with UX/UI designers, backend developers, and product managers to deliver cohesive and high-quality digital experiences. Participate in code reviews and contribute to discussions on best practices and technical approaches.\n\n· Utilize object-oriented programming techniques to design and implement reusable, modular components that align with front-end development standards and practices.\n\n· Engage in discussions about micro-frontend architecture and contribute to the development of modular, scalable front-end solutions that integrate seamlessly with other system components.\n\nWhat You Will Bring:\n\n· Bachelor's degree in computer science, computer engineering, Information Systems, or a related field.\n\n· At least 1-3 years of experience in software engineering\n\n· Experience with unit testing frameworks and knowledge of testing strategies and tools for ensuring code quality and reliability in front-end development.\n\n· Strong understanding of object-oriented programming principles and their application in front-end development to create clean, maintainable code.\n\n· Familiarity with backend technologies such as NestJS, SQL, and NoSQL databases, as well as experience with microservices architecture. Knowledge of Docker and Kubernetes for containerization and orchestration is also advantageous.\n\n· Understanding or experience with micro-frontend architecture for developing and managing modular frontend components effectively\n\nThe above information has been designed to indicate the general nature and level of work performed in the role. It is not designed to contain or be interpreted as a comprehensive inventory of all duties, responsibilities and qualifications required of employees assigned to this job. The full Job Description can be made available as part of the hiring process.\n\nAbout Walmart Global Tech:\n\nImagine working in an environment where one line of code can make life easier for hundreds of millions of people. That’s what we do at Walmart Global Tech. We’re a team of software engineers, data scientists, cybersecurity expert's and service professionals within the world’s leading retailer who make an epic impact and are at the forefront of the next retail disruption. People are why we innovate, and people power our innovations. We are people-led and tech-empowered.\n\nWe train our team in the skillsets of the future and bring in experts like you to help us grow. We have roles for those chasing their first opportunity as well as those looking for the opportunity that will define their career. Here, you can kickstart a great career in tech, gain new skills and experience for virtually every industry, or leverage your expertise to innovate at scale, impact millions and reimagine the future of retail.\n\nFlexible, hybrid work\n\nWe use a hybrid way of working with primary in office presence coupled with an optimal mix of virtual presence. We use our campuses to collaborate and be together in person, as business needs require and for development and networking opportunities. This approach helps us make quicker decisions, remove location barriers across our global team, be more flexible in our personal lives.\n\nBenefits:\n\nBeyond our great compensation package, you can receive incentive awards for your performance. Other great perks include a host of best-in-class benefits maternity and parental leave, PTO, health benefits, and much more.\n\nEqual Opportunity Employer:\n\nWalmart, Inc. is an Equal Opportunity Employer – By Choice. We believe we are best equipped to help our associates, customers and the communities we serve live better when we really know them. That means understanding, respecting and valuing diversity- unique styles, experiences, identities, ideas and opinions – while being inclusive of all people.\n\nThe above information has been designed to indicate the general nature and level of work performed in the role. It is not designed to contain or be interpreted as a comprehensive inventory of all responsibilities and qualifications required of employees assigned to this job. The full Job Description can be made available as part of the hiring process.\n\nAt Walmart, we offer competitive pay as well as performance-based bonus awards and other great benefits for a happier mind, body, and wallet. Health benefits include medical, vision and dental coverage. Financial benefits include 401(k), stock purchase and company-paid life insurance. Paid time off benefits include PTO (including sick leave), parental leave, family care leave, bereavement, jury duty, and voting. Other benefits include short-term and long-term disability, company discounts, Military Leave Pay, adoption and surrogacy expense reimbursement, and more.\n\n‎\n\n‎\n\n‎\nYou will also receive PTO and/or PPTO that can be used for vacation, sick leave, holidays, or other purposes. The amount you receive depends on your job classification and length of employment. It will meet or exceed the requirements of paid sick leave laws, where applicable.\n\n‎\n\nFor information about PTO, see https://one.walmart.com/notices.\n\n‎\n\n‎\nLive Better U is a Walmart-paid education benefit program for full-time and part-time associates in Walmart and Sam's Club facilities. Programs range from high school completion to bachelor's degrees, including English Language Learning and short-form certificates. Tuition, books, and fees are completely paid for by Walmart.\n\n‎\nEligibility requirements apply to some benefits and may depend on your job classification and length of employment. Benefits are subject to change and may be subject to a specific plan or program terms.\n\n‎\n\nFor information about benefits and eligibility, see One.Walmart.\n\n‎\nThe annual salary range for this position is $80,000.00-$155,000.00\n\n‎\nAdditional compensation includes annual or quarterly performance bonuses.\n\n‎\nAdditional compensation for certain positions may also include:\n\n‎\n\n‎\n- Stock\n\n‎\n\n‎\n\nMinimum Qualifications...\n\nOutlined below are the required minimum qualifications for this position. If none are listed, there are no minimum qualifications.\n\nOption 1: Bachelor's degree in computer science, computer engineering, computer information systems, software engineering, or related area.Option 2: 3 years’ experience in software engineering or related area.\n\nPreferred Qualifications...\n\nOutlined below are the optional preferred qualifications for this position. If none are listed, there are no preferred qualifications.\n\nCertification in Security+, Network+, GISF, or GSEC, We value candidates with a background in creating inclusive digital experiences, demonstrating knowledge in implementing Web Content Accessibility Guidelines (WCAG) 2.2 AA standards, assistive technologies, and integrating digital accessibility seamlessly. The ideal candidate would have knowledge of accessibility best practices and join us as we continue to create accessible products and services following Walmart’s accessibility standards and guidelines for supporting an inclusive culture.\n\nPrimary Location...\n\nPhyllis St. N Of Hwy 102, West Side Of Street, Bentonville, AR 72712, United States of America",
        "requirements": "At least 1-3 years of experience in software engineering\nExperience with unit testing frameworks and knowledge of testing strategies and tools for ensuring code quality and reliability in front-end development\nStrong understanding of object-oriented programming principles and their application in front-end development to create clean, maintainable code\nFamiliarity with backend technologies such as NestJS, SQL, and NoSQL databases, as well as experience with microservices architecture\nKnowledge of Docker and Kubernetes for containerization and orchestration is also advantageous\nUnderstanding or experience with micro-frontend architecture for developing and managing modular frontend components effectively\nOption 1: Bachelor's degree in computer science, computer engineering, computer information systems, software engineering, or related area\nOption 2: 3 years’ experience in software engineering or related area\nCertification in Security+, Network+, GISF, or GSEC, We value candidates with a background in creating inclusive digital experiences, demonstrating knowledge in implementing Web Content Accessibility Guidelines (WCAG) 2.2 AA standards, assistive technologies, and integrating digital accessibility seamlessly\nThe ideal candidate would have knowledge of accessibility best practices and join us as we continue to create accessible products and services following Walmart’s accessibility standards and guidelines for supporting an inclusive culture",
        "responsibilities": "As a Software Engineer II in the Customer Trust Gateway organization, you will play a key role in designing and developing high-quality, user-centric web applications\nYou will be responsible for implementing dynamic and responsive interfaces using modern front-end technologies such as React, CSS, and JavaScript\nThis includes collaborating with UX/UI designers and backend engineers to create seamless and intuitive user experiences that support our customer trust and privacy initiatives\nIn this role, you will leverage your front-end development skills to contribute to innovative solutions that align with our business objectives\nYou will have the opportunity to grow your expertise in technologies such as TypeScript and micro-frontend architecture while working on meaningful projects\nAdditionally, you will collaborate closely with your team to ensure that all front-end work is of high quality and adheres to best practices\nDesign and build responsive, user-friendly web applications using React, CSS, and JavaScript\nEnsure that interfaces are intuitive, performant, and meet the needs of our users\nWrite clean, maintainable code with a focus on using TypeScript to enhance reliability and scalability\nConduct unit testing to ensure the functionality and stability of your code\nWork closely with UX/UI designers, backend developers, and product managers to deliver cohesive and high-quality digital experiences\nParticipate in code reviews and contribute to discussions on best practices and technical approaches\nUtilize object-oriented programming techniques to design and implement reusable, modular components that align with front-end development standards and practices\nEngage in discussions about micro-frontend architecture and contribute to the development of modular, scalable front-end solutions that integrate seamlessly with other system components",
        "vacancy": 1,
        "apply_link": "https://careers.walmart.com/us/jobs/WD1968573-software-engineer-ii?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        "availability": "Hourly",
        "education": "Not Specified",
        "gender": "Not Specified",
        "age": "21+",
        "experience": "24 months",
        "language": "English"
    },
    {
        "id": "6scTrdi_fdEyMmHRAAAAAA==",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo--8eRalwgvj_2oxETMgJuZv3kYLP9P19L3EM&s=0",
        "name": "Netflix",
        "position": "Software Engineer 5 - TV UI Architecture and Performance",
        "location": "Unknown City, KS, US",
        "date": "30/09/2024",
        "deadline": "Wed Oct 30 2024",
        "fullTime": true,
        "partTime": false,
        "contract": false,
        "remote": false,
        "onsite": true,
        "minPrice": "You choose each year how much of your compensation you want in salary versus stock options",
        "maxPrice": "To determine your personal top of market compensation, we rely on market indicators and consider your specific job family, background, skills, and experience to determine your compensation in the market range",
        "per": "Month",
        "description": "Netflix is one of the world’s leading entertainment services with 278 million paid memberships in over 190 countries enjoying TV series, films and games across a wide variety of genres and languages. Members can play, pause and resume watching as much as they want, anytime, anywhere, and can change their plans at any time.\n\nThe Role\n\nThe Shared Client Foundations team builds UI architecture and frameworks which can be leveraged by product engineers, across the Android, iOS, TV, iOS and Web client platforms.\n\nThis specific role will be focused on TV, requiring expertise with JavaScript/TypeScript UI architecture and frameworks. However, we believe strong engineering aptitude transcends stacks, and providing the opportunity to explore architecture on other platforms is a unique aspect of this role.\n\nWe’re currently building solutions with JavaScript/TypeScript and React on TV & Web, Kotlin on Android, and Swift on iOS. We use GraphQL as our shared data access technology.\n\nWe provide ergonomic solutions for UI engineers to access data, configure applications, create server-driven UIs and optimize performance. We work on client side and server side solutions - wherever a problem takes us. And that’s just scratching the surface.\n\nMany of the projects we take on are broad cross-functional efforts, allowing you to extend beyond our team and engage with teams across the company. We’re a team of peers. Everyone has the opportunity to scope, architect, implement, and support the solutions we deliver.\n\nSome of the things we’re excited to be working on currently:\n• Building the ideal cross-platform data access architecture for Netflix applications\n• Creating a Server Driven UI architecture which accelerates app experimentation\n• Delivering frameworks to optimize feature-flag based UI development\n\nThe Team\n\nThe Shared Client Foundations team builds shared UI architecture and frameworks which power the Netflix TV, iOS, Android and Web applications on devices ranging from web browsers, mobile phones and tablets, to streaming sticks, cable boxes, Smart TVs and game consoles.\n\nWe’re passionate about creating elegantly designed, highly performant UI architectures which empower engineers to build amazing UI experiences used by millions of users across the globe. We partner closely with teams across Netflix to help us deliver solutions which make UI development efficient and enjoyable.\n\nDiverse and inclusive teams are strong teams. We encourage those with varied identities, backgrounds, and experiences to apply. We believe that creating a sense of belonging allows us to be our best selves, which in turn helps us produce our best work. We rely on our unique individual strengths to help each other grow.\n\nWe have a distributed team, with some teammates working remotely, and some colocated in the Los Gatos, CA office. The team is committed to being ‘remote-inclusive’ and believe it’s about the work you do, and the relationships you build. Where you can best do that from is up to you.\n\nYou\n\nPeople who do well on the team are self-motivated engineers with a passion for driving technology innovation rooted in business and customer needs. Great analytical and technical skills form a solid foundation. But more importantly, we look for engineers who understand that there are rarely any absolutes when it comes to technology. The ability to engage in meaningful discussions about use cases, prioritization and technical challenges with colleagues, while thoughtfully weighing trade-offs across multiple solutions is a skill we value highly.\n\nAll of this, so that Netflix members can immerse themselves in the stories they care about, on the devices they love, from whichever part of the world they call home. Without the technology behind it all ever getting in the way.\n\nIf this resonates with you, we’d love to talk!\n\nWhat’s Different About Us\n\nScale, Impact\n• Hundreds of Engineers : You’ll be improving UI development velocity for over 100 engineers...\n• Millions of Users : creating best-in-class streaming UIs used by over 100M users...\n• Thousands of Devices : across a wide spectrum of devices...\n• Globally : in almost every country in the world.\n\nUnique Technical Challenges\n\nWe build framework solutions which are flexible enough to withstand the span of use cases introduced by rapid A/B test development, across a varied client, server and network performance landscape, all while being ergonomic to use for the engineers we support.\n\nCollaboration and Communication\n\nIt’s not all about the tech. We highly value the skills required to build strong relationships and collaborate effectively.\n\nFreedom, Responsibility, Ownership\n\nWe believe in providing engineers with the business context they need, and then giving them the freedom and responsibility to define project scope, define/debate architecture, determine trade-offs, and figure out the implementation details.\n\nOur Culture\n\nLastly, but most importantly, we live by our values.\n\nWhat Sets You Apart\n• You’re passionate about writing elegantly designed, maintainable, performant software\n• You enjoy pushing the boundaries of what technology can do, and exploring uncharted waters\n• You love the idea of your work empowering other engineers and strive to understand their use cases\n• Colleagues appreciate the unique perspectives and balanced views you bring to collaborations\n• You value the opinion of others when fleshing out solutions, to fill out your blind spots\n• You know that there is rarely a single ‘right’ solution, and are thoughtful about trade-offs\n• You understand that it is really about solving problems. A language, framework or library choice is just a means to an end.\n\nOur compensation structure consists solely of an annual salary; we do not have bonuses. You choose each year how much of your compensation you want in salary versus stock options. To determine your personal top of market compensation, we rely on market indicators and consider your specific job family, background, skills, and experience to determine your compensation in the market range. The range for this role is $100,000 - $720,000.\n\nNetflix provides comprehensive benefits including Health Plans, Mental Health support, a 401(k) Retirement Plan with employer match, Stock Option Program, Disability Programs, Health Savings and Flexible Spending Accounts, Family-forming benefits, and Life and Serious Injury Benefits. We also offer paid leave of absence programs. Full-time hourly employees accrue 35 days annually for paid time off to be used for vacation, holidays, and sick paid time off. Full-time salaried employees are immediately entitled to flexible time off. See more detail about our Benefits here.\n\nNetflix is a unique culture and environment. Learn more here.\n\nWe are an equal-opportunity employer and celebrate diversity, recognizing that diversity of thought and background builds stronger teams. We approach diversity and inclusion seriously and thoughtfully. We do not discriminate on the basis of race, religion, color, ancestry, national origin, caste, sex, sexual orientation, gender, gender identity or expression, age, disability, medical condition, pregnancy, genetic makeup, marital status, or military service.\n\nJob is open for no less than 7 days and will be removed when the position is filled.",
        "requirements": "People who do well on the team are self-motivated engineers with a passion for driving technology innovation rooted in business and customer needs\nGreat analytical and technical skills form a solid foundation\nBut more importantly, we look for engineers who understand that there are rarely any absolutes when it comes to technology\nYou’re passionate about writing elegantly designed, maintainable, performant software\nYou enjoy pushing the boundaries of what technology can do, and exploring uncharted waters\nYou love the idea of your work empowering other engineers and strive to understand their use cases\nYou value the opinion of others when fleshing out solutions, to fill out your blind spots\nYou know that there is rarely a single ‘right’ solution, and are thoughtful about trade-offs\nYou understand that it is really about solving problems",
        "responsibilities": "The Shared Client Foundations team builds UI architecture and frameworks which can be leveraged by product engineers, across the Android, iOS, TV, iOS and Web client platforms\nThis specific role will be focused on TV, requiring expertise with JavaScript/TypeScript UI architecture and frameworks\nWe work on client side and server side solutions - wherever a problem takes us\nBuilding the ideal cross-platform data access architecture for Netflix applications\nCreating a Server Driven UI architecture which accelerates app experimentation\nDelivering frameworks to optimize feature-flag based UI development\nHundreds of Engineers : You’ll be improving UI development velocity for over 100 engineers..",
        "vacancy": 1,
        "apply_link": "https://explore.jobs.netflix.net/careers/job/790299319827?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        "availability": "Hourly",
        "education": "Not Specified",
        "gender": "Not Specified",
        "age": "21+",
        "experience": "3 - 5 Years",
        "language": "English"
    },
    {
        "id": "SnCwKBjholdhPuwpAAAAAA==",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgVVSk_QhTuQmEEn1ZvGqho0kUG1HUYhqIf624&s=0",
        "name": "Epic",
        "position": "Software Engineer",
        "location": "Norman, OK, US",
        "date": "03/10/2024",
        "deadline": "Thu Nov 28 2024",
        "fullTime": true,
        "partTime": false,
        "contract": false,
        "remote": false,
        "onsite": true,
        "minPrice": "We offer comprehensive benefits to keep you healthy and happy as you grow in your life and career, and your merit-based compensation will reflect the impact your work has on the company and our customers",
        "maxPrice": "You'll also be eligible for annual raises and bonuses, as well as stock grants, which give you an even greater stake in the success of Epic and our customers",
        "per": "Month",
        "description": "Please note that this position is based on our campus in Madison, WI, and requires relocation to the area. We recruit nationally and provide financial relocation assistance.\n\nCode that saves lives.\n\nAs a software developer at Epic, you’ll write software that impacts the lives of 75% of Americans and 300 million patients around the world. Working in your own office, surrounded by thousands of high-caliber developers, you’ll use modern development methodologies and employ user-centered design, analytics, and machine learning tools to drive innovation in healthcare. Using leading-edge technologies and languages like JS, TS, and C#, you’ll invent better ways to reduce medical errors, streamline record sharing between hospitals, and provide the quality of care a patient deserves.\n\nWrite software for the most innovative health systems on the planet.\n\nThe top-ranked health systems in U.S. News and World Report are Epic customers. Our community includes major systems like the Mayo Clinic, Johns Hopkins, Cleveland Clinic, and Kaiser Permanente, as well as leading academic medical centers at the University of Wisconsin, University of Michigan, University of California, University of Texas, The Ohio State University, and many more.\n\nExperience our state-of-the-art campus, eat delicious food, and travel the world.\n\nWe don’t believe in cubicles. (Well, we believe they exist, but…) Our uniquely themed campus was designed to heighten your ability to get stuff done in your office, a conference room, or by the fireplace in a comfy chair. For lunch, visit King’s Cross or Cassiopeia for a wide array of meal options, or go to one of our smaller, themed bistros, featuring wood-rotisserie, pan-Asian, and Latin-inspired cuisine. All meals are restaurant-quality but cost only a few dollars, and they’re prepared by a team comprised of kitchen talent from restaurants around the country. And, after five years here, you’ll earn a four-week sabbatical anywhere in the world. Staff have kayaked in Patagonia, attended a Beyoncé concert in Ireland, built a library in Tanzania, and run a marathon in Antarctica.\n\nLive affordably in a city known for its rising tech talent.\n\nEpic is located just outside Madison, Wisconsin, which is the second fastest growing market for tech talent in the United States, home to the state capital, and the University of Wisconsin. Madison has received accolades for being the greenest city in America (NerdWallet), the best city for renters (SmartAsset), fittest city in America (Fitbit), and, for the gamers, is one of a handful of US cities to have a Killer Queen arcade game, located at Madison’s first arcade bar.\n\nMore than just important work.\n\nWe offer comprehensive benefits to keep you healthy and happy as you grow in your life and career, and your merit-based compensation will reflect the impact your work has on the company and our customers. You'll also be eligible for annual raises and bonuses, as well as stock grants, which give you an even greater stake in the success of Epic and our customers. Healthcare is global, and building the best ideas from around the world into Epic software is a point of pride. As an Equal Opportunity Employer, we know that inclusive teams design software that supports the delivery of quality care for all patients, so diversity, equity, and inclusion are written into our principles. Research has shown that job-seekers who are women, LGBTQ+, or members of historically underrepresented communities are less likely to apply for roles they don't seem completely qualified for, so we encourage all who are interested to apply. Please see our full non-discrimination statement at https //careers.epic.com/EEO.\n• Relocation to the Madison, WI area (Reimbursed)\n• BS/BA or greater in Computer Science, Mathematics, Software Engineering, Computer Engineering, or a related field\n• A history of academic excellence or professional success\n• Eligible to work in the United States without visa sponsorship (persons with appropriate qualifications and eligible for TN status under NAFTA may apply)\n• COVID-19 vaccination",
        "requirements": "BS/BA or greater in Computer Science, Mathematics, Software Engineering, Computer Engineering, or a related field\nA history of academic excellence or professional success\nEligible to work in the United States without visa sponsorship (persons with appropriate qualifications and eligible for TN status under NAFTA may apply)",
        "responsibilities": "No responsibilities specified",
        "vacancy": 1,
        "apply_link": "https://www.linkedin.com/jobs/view/software-engineer-at-epic-3986111783?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        "availability": "Hourly",
        "education": "Graduate",
        "gender": "Not Specified",
        "age": "21+",
        "experience": "3 - 5 Years",
        "language": "English"
    },
    {
      "id": "sCF6WuDrdefkI7PLAAAAAA==",
      "image": "https://cdn.nium.com/app/uploads/2022/06/07211301/Nium_Lockup_Blue_Black_RGB.png",
      "name": "Nium",
      "position": "SDE I",
      "location": "San Francisco, CA, US",
      "date": "31/05/2024",
      "deadline": "September 20, 2025",
      "fullTime": true,
      "partTime": false,
      "contract": false,
      "remote": false,
      "onsite": true,
      "minPrice": "Salary ranges are dependent on a variety of factors, including skills, qualifications, experience, and geographic location",
      "maxPrice": "Certain roles may offer additional incentives including but not limited to equity and bonus",
      "per": "Month",
      "description": "Nium, Global Leader in Payments\n\nNium, the global leader in real-time, cross-border payments, was founded on the mission to deliver the global payments infrastructure of tomorrow, today. With the onset of the global economy, its payments infrastructure is shaping how banks, fintechs, and businesses everywhere collect, convert, and disburse funds instantly across borders.\n\nIts payout network supports 100 currencies and spans 220+ markets, 100 of which in real-time. Funds can be disbursed to accounts, wallets, and cards and collected locally in 35 markets. Nium's growing card issuance business is already available in 34 countries. Nium holds regulatory licenses and authorizations in more than 40 countries, enabling seamless onboarding, rapid integration, and compliance – independent of geography. The company is co-headquartered in San Francisco and Singapore.\n\nAbout the Team\n\nNium's Engineering team is responsible for building and maintaining the company's global financial infrastructure. We are a team of talented engineers who are passionate about creating innovative and scalable solutions that help Nium deliver on its mission of making money movement seamless and borderless.\n\nAbout the Role\n\nOur ideal candidate has deep experience in building scalable and reliable backend systems, services and APIs that deliver value to our customers. This role will make impactful contributions and will proactively identify gaps and future work for the team.\n\nKey Responsibilities\n• Deliver and own large features end-to-end\n• Collaborate with our product team to deliver high impact for our customers\n• Proactively identify ways to monitor the quality, reliability, and security of our systems\n• Abide by engineering best practices\n\nRequirements\n• 1-2 years of backend engineering experience, recommended not required.\n• Experience building and operating highly available backend distributed systems\n• Proficiency in at least one of Java, Python, C++, C#, Golang\n• Strong communication (written and verbal) and interpersonal skills\n• Thrive in a collaborative and fast-paced environment\n• Passion for turning business and product ideas into engineering solutions\n\n$112,000 - $154,000 a year\nSalary ranges are dependent on a variety of factors, including skills, qualifications, experience, and geographic location. Certain roles may offer additional incentives including but not limited to equity and bonus. Your recruiter is happy to share more information about the salary range specific to your working location and other factors at any stage of the hiring process!\n\nDepending on your location, certain laws may regulate the way Nium manages the data of candidates. By submitting your job application, you are agreeing and acknowledging that you have read and understand our Candidate Privacy Notice\n\nWhat we offer at Nium\n\nWe Value Performance: Through competitive salaries, performance bonuses, sales commissions, equity for specific roles and recognition programs, we ensure that all our employees are well rewarded and incentivized for their hard work.\n\nWe Care: The wellness of Nium’ers is our #1 priority. We offer medical coverage along with 24/7 employee assistance program, generous vacation programs including our year-end shut down. We also provide a flexible hybrid working environment (3 days per week in the office).\n\nWe Upskill Ourselves: We are curious, and always want to learn more with a focus on upskilling ourselves. We provide role-specific training, internal workshops, and a learning stipend.\n\nWe Constantly Innovate: Since our inception, Nium has received constant recognition and awards for how we approach both our business and talent opportunities. Check out CNBC World’s Top Fintech Companies 2024.\n\nWe Celebrate Together: We recognize that work is also about creating great relationships with each other. We celebrate together with company-wide social events, team bonding activities, happy hours, team offsites, and much more!\n\nWe Thrive With Diversity: Nium is truly a global company, with more than 33 nationalities, based in 18+ countries and more than 10 office locations. As an equal opportunity employer, we are committed to providing a safe and welcoming environment for everyone.\n\nFor more detailed region-specific benefits: https://www.nium.com/careers#careers-perks\n\nFor more information, visit www.nium.com.\n\nNium provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, gender, sexual orientation, national origin, age, disability, or veteran status. In addition to federal law requirements, Nium complies with applicable state and local laws governing non-discrimination in employment in every location in which the company operates. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation, and training. Nium expressly prohibits any form of workplace harassment based on race, color, religion, gender, sexual orientation, national origin, age, disability, or veteran status.",
      "requirements": "1-2 years of backend engineering experience, recommended not required\nExperience building and operating highly available backend distributed systems\nProficiency in at least one of Java, Python, C++, C#, Golang\nStrong communication (written and verbal) and interpersonal skills\nThrive in a collaborative and fast-paced environment\nPassion for turning business and product ideas into engineering solutions",
      "responsibilities": "This role will make impactful contributions and will proactively identify gaps and future work for the team\nDeliver and own large features end-to-end\nCollaborate with our product team to deliver high impact for our customers\nProactively identify ways to monitor the quality, reliability, and security of our systems\nAbide by engineering best practices",
      "vacancy": 1,
      "apply_link": "https://jobs.lever.co/nium/bc54a3d5-489f-443c-9cc3-1575bf60ab85?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      "availability": "Hourly",
      "education": "Not Specified",
      "gender": "Not Specified",
      "age": "21+",
      "experience": "12 months",
      "language": "English"
  },
  {
          "id": "fXvn0sUgyW-l7Fe1AAAAAA==",
          "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKHGq9BfqmspjTPUHLQ_UfRJzW89HjbqEwcfoQ&s=0",
          "name": "myGwork - LGBTQ+ Business Community",
          "position": "SDE II - Financial Risk Mitigation, Payment Instrument Trust",
          "location": "Tempe, AZ, US",
          "date": "04/10/2024",
          "deadline": "Sun Nov 03 2024",
          "fullTime": true,
          "partTime": false,
          "contract": false,
          "remote": false,
          "onsite": true,
          "minPrice": "Dependent on the position offered, equity, sign-on payments, and other forms of compensation may be provided as part of a total compensation package, in addition to a full range of medical, financial, and/or other benefits",
          "maxPrice": "N/A",
          "per": "Month",
          "description": "This job is with Amazon, an inclusive employer and a member of myGwork – the largest global platform for the LGBTQ+ business community. Please do not contact the recruiter directly.\n\nDescription\n\nAmazon has hundreds of millions of customers, sellers, and developers all over the world that rely on Amazon products and services. Selling Partner Services (SPS) is the organization that constantly makes high judgment decisions across a wide breadth of constituents. Preserving Trust in Amazon with every customer, every transaction, every second is our mission. We do this by identifying and removing bad actors from the platform, while supporting a best-in-class customer experience. We ensure that Amazon is a safe and trustworthy place to shop and an amazing place to build a successful business selling products.\n\nAs the Engineering team in SPS organization, we create next-gen services ahead of the industry standard & cloud standard solutions with end-to-end highly automated and highly intelligent engineering solutions. We own & build environments that will drive speed, quality, and efficiency across SPS and Amazon. Not only do we leverage industry leading technology, we innovate our own solutions that are ahead of the curve (and necessarily so to stay ahead of bad actors). We support many partners in this journey. We face constant trade-offs and competing objectives that we need to balance. We do all of this at high scale through technology and science. We are a large organization that leads on innovation in many areas, and so we play a critical role in helping Amazon more broadly beyond our own goals.\n\nKey job responsibilities\n• Develop large scale, high performance, high reliability systems.\n• Work as the owner of the system and operate excellent to provide stable and robust services to customers and other teams.\n• Innovate based on new ideas and build comprehensive system/features.\n\nAbout The Team\n\nHere at Selling Partner Services, we embrace our differences. We are committed to furthering our culture of inclusion. We have 14 employee-led affinity groups, reaching 10,000+ employees in chapters globally. We have innovative benefit offerings, and we host annual and ongoing learning experiences, including our DEI Ambassador Program. Amazon's culture of inclusion is reinforced within our 16 Leadership Principles, which remind team members to seek diverse perspectives, learn and be curious, and earn trust.\n\nBasic Qualifications\n• 3+ years of non-internship professional software development experience\n• 2+ years of non-internship design or architecture (design patterns, reliability and scaling) of new and existing systems experience\n• Experience programming with at least one software programming language\n\nPreferred Qualifications\n• 3+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience\n• Bachelor's degree in computer science or equivalent\n\nAmazon is committed to a diverse and inclusive workplace. Amazon is an equal opportunity employer and does not discriminate on the basis of race, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other legally protected status. For individuals with disabilities who would like to request an accommodation, please visit https://www.amazon.jobs/en/disability/us.\n\nOur compensation reflects the cost of labor across several US geographic markets. The base pay for this position ranges from $129,300/year in our lowest geographic market up to $223,600/year in our highest geographic market. Pay is based on a number of factors including market location and may vary depending on job-related knowledge, skills, and experience. Amazon is a total compensation company. Dependent on the position offered, equity, sign-on payments, and other forms of compensation may be provided as part of a total compensation package, in addition to a full range of medical, financial, and/or other benefits. For more information, please visit https://www.aboutamazon.com/workplace/employee-benefits. This position will remain posted until filled. Applicants should apply via our internal or external career site.",
          "requirements": "3+ years of non-internship professional software development experience\n2+ years of non-internship design or architecture (design patterns, reliability and scaling) of new and existing systems experience\nExperience programming with at least one software programming language",
          "responsibilities": "Develop large scale, high performance, high reliability systems\nWork as the owner of the system and operate excellent to provide stable and robust services to customers and other teams\nInnovate based on new ideas and build comprehensive system/features",
          "vacancy": 1,
          "apply_link": "https://www.linkedin.com/jobs/view/sde-ii-financial-risk-mitigation-payment-instrument-trust-at-mygwork-lgbtq%2B-business-community-4042714646?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          "availability": "Hourly",
          "education": "Graduate",
          "gender": "Not Specified",
          "age": "21+",
          "experience": "36 months",
          "language": "English"
      },
      {
        "id": "58iHlbUtv4xSvN4nAAAAAA==",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFYWIXIwcm3S5ZuYYLRCfV0D-WyMTHRl2p2vZ9&s=0",
        "name": "O'Reilly Auto Parts",
        "position": "Software Engineer",
        "location": "Springfield, MO, US",
        "date": "19/09/2024",
        "deadline": "September 20, 2025",
        "fullTime": true,
        "partTime": false,
        "contract": false,
        "remote": false,
        "onsite": true,
        "minPrice": "Additional compensation includes annual, quarterly performance, or premiums may be paid in amounts ranging per hour in specific circumstances",
        "maxPrice": "Premiums may be based on schedule, facility, season, or specific work performed",
        "per": "Month",
        "description": "Compensation Pay Range:\n$104,000.00 - $130,000.00\n\nThe actual hourly rate will equal or exceed the required minimum wage applicable to the job location. Additional compensation includes annual, quarterly performance, or premiums may be paid in amounts ranging per hour in specific circumstances. Premiums may be based on schedule, facility, season, or specific work performed. Multiple premiums may apply if applicable criteria are met.\n\nA software engineer will utilize expert knowledge in at least one business or technology function. This position will work with a high degree of independence and develop information systems to support the business. Engineers will focus on the design or integration of various software systems, databases, and third-party packages.\n\nESSENTIAL JOB FUNCTIONS\n\nTakes leadership role in guiding projects through the complete software development life cycle\n\nLeads code design efforts to ensure solutions are performant, scalable, and meet intended business outcomes.\n\nResponsible for multiple software applications and managing tasks and resources while utilizing modern project management principles.\n\nParticipates in or leads the development of multiple projects at one time.\n\nConducts code reviews and ensures coding best practices are being followed while developing new or modifying existing software using coding best practices.\n\nRecommend software improvements and changes to systems, as needed.\n\nMay approve software to be deployed to production systems.\n\nPerform software and data analysis to uncover issues and solve complex problems that span multiple systems.\n\nLead various meetings to gather software requirements and project details.\n\nConduct software demos to educate and train others in the use of software.\n\nDebug and correct complex software defects.\n\nCreate or update advanced project documentation.\n\nTest software to validate accuracy of code and high-quality software systems.\n\nAdvanced understanding of the software and system(s) supported by their team, as well as the overall company business\n\nParticipate in quarterly goal reviews, project priority discussions, and provide feedback.\n\nMentor software developers or interns.\n\nConduct project lessons learned activities and code review sessions.\n\nProvide project updates and report project time as needed.\n\nOther duties as assigned.\n\nSKILLS/EDUCATION/KNOWLEDGE/EXPERIENCE/ABILITIES\nRequired:\n\n7+ years of software development experience\n\nBachelor’s degree in Computer Science, Information Systems or related field (5+ years O’Reilly software development experience will be considered in lieu of degree)\n\nAdvanced understanding of change management and the O’Reilly change control process and procedures\n\nAdvanced knowledge of Project Development Life Cycle (PDLC) and Software Development Life Cycle (SDLC)\n\nSolid understanding of secure coding techniques and best practices\n\nStrong ability to articulate advanced technical concepts, write technical documentation, and teach others\n\nExpert knowledge in software debugging and testing, complex computer systems (multiple programs, databases, communications etc.), and analysis and design.\n\nAdvanced problem-solving skills with the ability to manage multiple tasks at one time\n\nStrong verbal and written communications skills with the ability to lead and get results from others\n\nMust be able to learn independently but also work well in a team environment\n\nFlexible scheduling availability including nights and weekend\nDesired:\n\nEducation in leadership and or teambuilding\n\nEducation in Project Management and Business Analysis\n\nAdvanced technical training or certifications related to scope of work\n\n#LI-Remote\n\n#LI-RT1\n\nO’Reilly Auto Parts has a proven track record of growth and stability. O’Reilly is full of successful career stories and believes in a strong promote-from-within philosophy, encouraging you to grow your career along with the organization.\n\nTotal Compensation Package:\n• Competitive Wages & Paid Time Off\n• Stock Purchase Plan & 401k with Employer Contributions Starting Day One\n• Medical, Dental, & Vision Insurance with Optional Flexible Spending Account (FSA)\n• Team Member Health/Wellbeing Programs\n• Tuition Educational Assistance Programs\n• Opportunities for Career Growth\n\nO’Reilly Auto Parts is an equal opportunity employer. Hiring decisions are administered without regard to race, color, creed, religion, sex, pregnancy, sexual orientation, gender identity, age, national origin, ancestry, citizenship status, disability, veteran status, genetic information, or any other basis protected by applicable federal, state or local law.\nReasonable Accommodations: Qualified individuals with known disabilities may be entitled to reasonable accommodation under the Americans with Disabilities Act and certain state or local laws.",
        "requirements": "Bachelor’s degree in Computer Science, Information Systems or related field (5+ years O’Reilly software development experience will be considered in lieu of degree)\nAdvanced understanding of change management and the O’Reilly change control process and procedures\nAdvanced knowledge of Project Development Life Cycle (PDLC) and Software Development Life Cycle (SDLC)\nSolid understanding of secure coding techniques and best practices\nStrong ability to articulate advanced technical concepts, write technical documentation, and teach others\nExpert knowledge in software debugging and testing, complex computer systems (multiple programs, databases, communications etc.), and analysis and design\nAdvanced problem-solving skills with the ability to manage multiple tasks at one time\nStrong verbal and written communications skills with the ability to lead and get results from others\nMust be able to learn independently but also work well in a team environment\nFlexible scheduling availability including nights and weekend\nEducation in leadership and or teambuilding\nEducation in Project Management and Business Analysis\nAdvanced technical training or certifications related to scope of work",
        "responsibilities": "A software engineer will utilize expert knowledge in at least one business or technology function\nThis position will work with a high degree of independence and develop information systems to support the business\nEngineers will focus on the design or integration of various software systems, databases, and third-party packages\nTakes leadership role in guiding projects through the complete software development life cycle\nLeads code design efforts to ensure solutions are performant, scalable, and meet intended business outcomes\nResponsible for multiple software applications and managing tasks and resources while utilizing modern project management principles\nParticipates in or leads the development of multiple projects at one time\nConducts code reviews and ensures coding best practices are being followed while developing new or modifying existing software using coding best practices\nRecommend software improvements and changes to systems, as needed\nMay approve software to be deployed to production systems\nPerform software and data analysis to uncover issues and solve complex problems that span multiple systems\nLead various meetings to gather software requirements and project details\nConduct software demos to educate and train others in the use of software\nDebug and correct complex software defects\nCreate or update advanced project documentation\nTest software to validate accuracy of code and high-quality software systems\nAdvanced understanding of the software and system(s) supported by their team, as well as the overall company business\nParticipate in quarterly goal reviews, project priority discussions, and provide feedback\nMentor software developers or interns\nConduct project lessons learned activities and code review sessions\nProvide project updates and report project time as needed\nOther duties as assigned",
        "vacancy": 1,
        "apply_link": "https://careers.oreillyauto.com/us/en/job/R73962/Software-Engineer?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        "availability": "Hourly",
        "education": "Not Specified",
        "gender": "Not Specified",
        "age": "21+",
        "experience": "84 months",
        "language": "English"
    },
    {
      "id": "hiDgE1xHEJ9B6E0eAAAAAA==",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsn16nYJihCIJvdi3OHRrGY9HnCQAJptZhag_z&s=0",
      "name": "Facebook",
      "position": "Software Engineer",
      "location": "Oklahoma City, OK, US",
      "date": "10/09/2024",
      "deadline": "Sat Nov 09 2024",
      "fullTime": true,
      "partTime": false,
      "contract": false,
      "remote": false,
      "onsite": true,
      "minPrice": "$210,801/year to $240,240/year + bonus + equity + benefits",
      "maxPrice": "N/A",
      "per": "Month",
      "description": "• *Summary:**\n\nMeta Platforms, Inc. (Meta), formerly known as Facebook Inc., builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps and services like Messenger, Instagram, and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology. To apply, click “Apply to Job” online on this web page.\n• *Required Skills:**\n\nSoftware Engineer Responsibilities:\n\n1. Help build the next generation of systems behind Meta’s products, create web and/or mobile applications that reach over two billion people, and build high-volume servers to support content.\n\n2. Harness passion for technology and graduate-level knowledge and help build highly-scalable performant solutions.\n\n3. Make use of graduate-level knowledge of algorithms and core computer science concepts and ability to apply knowledge to real world systems.\n\n4. Without direct assistance, make the most of ability to recognize and match patterns from different areas of computer science in production systems and hone skill in making architectural decisions.\n\n5. Employ deep knowledge in at least one area: data processing, programming languages, databases, networking, operating systems, computer graphics, or human computer interaction.\n\n6. Design core, backend software components, using primarily C/C++, Java, PHP and Hack.\n\n7. Interface with other teams to incorporate their innovations and vice versa.\n\n8. Conduct design and code reviews.\n\n9. Analyze and improve efficiency, scalability, and stability of various system resources.\n\n10. Telecommuting is permitted from anywhere in the United States.\n• *Minimum Qualifications:**\n\nMinimum Qualifications:\n\n11. Master's degree or foreign equivalent in Computer Science, Computer Engineering, or a related field and 24 months of experience in the job offered or in a related occupation. Experience must include 24 months in each of the following:\n\n12. 1. Java\n\n13. 2. Software development tools: Code editors (VIM or Emacs), and revision control systems (Subversion, GIT, or Perforce)\n\n14. 3. Linux\n\n15. 4. Building highly-scalable performant solutions\n\n16. 5. Data processing, programming languages, databases, networking, operating systems, computer graphics, or human-computer interaction\n\n17. 6. Applying algorithms and core computer science concepts to real world systems as evidenced by recognizing and matching patterns from different areas of computer science in production systems\n\n18. 7. Distributed systems.\n• *Public Compensation:**\n\n$210,801/year to $240,240/year + bonus + equity + benefits\n• *Industry:** Internet\n• *Equal Opportunity:**\n\nMeta is proud to be an Equal Employment Opportunity and Affirmative Action employer. We do not discriminate based upon race, religion, color, national origin, sex (including pregnancy, childbirth, or related medical conditions), sexual orientation, gender, gender identity, gender expression, transgender status, sexual stereotypes, age, status as a protected veteran, status as an individual with a disability, or other applicable legally protected characteristics. We also consider qualified applicants with criminal histories, consistent with applicable federal, state and local law. Meta participates in the E-Verify program in certain locations, as required by law. Please note that Meta may leverage artificial intelligence and machine learning technologies in connection with applications for employment.\n\nMeta is committed to providing reasonable accommodations for candidates with disabilities in our recruiting process. If you need any assistance or accommodations due to a disability, please let us know at accommodations-ext@fb.com.",
      "requirements": "Harness passion for technology and graduate-level knowledge and help build highly-scalable performant solutions\nEmploy deep knowledge in at least one area: data processing, programming languages, databases, networking, operating systems, computer graphics, or human computer interaction\nMaster's degree or foreign equivalent in Computer Science, Computer Engineering, or a related field and 24 months of experience in the job offered or in a related occupation\nExperience must include 24 months in each of the following:\nSoftware development tools: Code editors (VIM or Emacs), and revision control systems (Subversion, GIT, or Perforce)\nMeta participates in the E-Verify program in certain locations, as required by law",
      "responsibilities": "Help build the next generation of systems behind Meta’s products, create web and/or mobile applications that reach over two billion people, and build high-volume servers to support content\nWithout direct assistance, make the most of ability to recognize and match patterns from different areas of computer science in production systems and hone skill in making architectural decisions\nInterface with other teams to incorporate their innovations and vice versa\nConduct design and code reviews\nAnalyze and improve efficiency, scalability, and stability of various system resources",
      "vacancy": 1,
      "apply_link": "https://www.localjobs.com/job/oklahoma-city-ok-software-engineer?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      "availability": "Hourly",
      "education": "Not Specified",
      "gender": "Not Specified",
      "age": "21+",
      "experience": "24 months",
      "language": "English"
    },
    {
        "id": "7ebSNi34ZTWWXA89AAAAAA==",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGoVAHERxx_QS2tHxz8qqZMC7kPaFGM7akPf_Z&s=0",
        "name": "Garmin International, Inc.",
        "position": "Software Engineer 1",
        "location": "Olathe, KS, US",
        "date": "05/09/2024",
        "deadline": "Fri Sep 05 2025",
        "fullTime": true,
        "partTime": false,
        "contract": false,
        "remote": false,
        "onsite": true,
        "minPrice": "N/A",
        "maxPrice": "N/A",
        "per": "Month",
        "description": "Overview\n\nWe are seeking a full-time Software Engineer 1 in our Olathe Support Center, KS location. In this role, you will be supporting Garmin’s Operations team by building upon existing software solutions to develop basic software for Garmin products and/or applications.\n\nEssential Functions\n• Performs new product and/or application software design and development as well as maintenance activities for products and/or applications using Vue, Node, Java or other selected languages\n• Troubleshoots basic issue reports, reproduces issues, evaluates technical cause, and implements and tests software solutions\n• Applies design standards and procedures using appropriate engineering tools to document and implement basic designs in an organized manner\n• Collaborates and adds value through participation in peer code reviews, providing comments and suggestions\n• Supports working hours as part of a rotating schedule to provide on call support of Garmin’s 24/7 operations\n\nBasic Qualifications\n• Bachelor’s Degree in Computer Science, Electrical Engineering, Computer Engineering, Software Engineering, Math or related field OR an equivalent combination of education and experience\n• Excellent academics (cumulative GPA greater than or equal to 3.0 as a general rule)\n• Demonstrated knowledge, education, experience and/or training necessary to develop basic software in Node, Vue, Express, TypeScript, Java, Spring and Spring Boot or other selected languages\n\nDesired Qualifications\n• Outstanding academics (cumulative GPA greater than or equal to 3.5)\n• Previous internship experience in design and development of software applications OR a minimum of 1-year work experience\n• Basic experience with Relational Databases and NoSQL data stores\n• Familiarity with component-based web frameworks (Vue, Express, Spring)\n• Familiarity with test tools including Junit, Mockito in implementing unit tests and integration test suites.\n• Previous experience working in a team environment\n• Experience using build tools like Maven or Jenkins\n• Experience with version control systems (GIT)\n• A strong team player that cares about collective team success\n• Drive to understand the business units supporting, Product Support, Product Quality, Manufacturing and Logistics teams\n\nGarmin International is an equal opportunity employer. Qualified applicants will receive consideration for employment without regard to race, religion, color, national origin, citizenship, sex, sexual orientation, gender identity, veteran’s status, age or disability.\n\nThis position is eligible for Garmin's benefit program. Details can be found here: Garmin Benefits",
        "requirements": "Bachelor’s Degree in Computer Science, Electrical Engineering, Computer Engineering, Software Engineering, Math or related field OR an equivalent combination of education and experience\nExcellent academics (cumulative GPA greater than or equal to 3.0 as a general rule)\nDemonstrated knowledge, education, experience and/or training necessary to develop basic software in Node, Vue, Express, TypeScript, Java, Spring and Spring Boot or other selected languages",
        "responsibilities": "In this role, you will be supporting Garmin’s Operations team by building upon existing software solutions to develop basic software for Garmin products and/or applications\nPerforms new product and/or application software design and development as well as maintenance activities for products and/or applications using Vue, Node, Java or other selected languages\nTroubleshoots basic issue reports, reproduces issues, evaluates technical cause, and implements and tests software solutions\nApplies design standards and procedures using appropriate engineering tools to document and implement basic designs in an organized manner\nCollaborates and adds value through participation in peer code reviews, providing comments and suggestions\nSupports working hours as part of a rotating schedule to provide on call support of Garmin’s 24/7 operations",
        "vacancy": 1,
        "apply_link": "https://careers.garmin.com/jobs/14123?lang=en-us&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        "availability": "Hourly",
        "education": "Not Specified",
        "gender": "Not Specified",
        "age": "21+",
        "experience": "12 months",
        "language": "English"
    },
      {
          "id": "lmu_A9RrhEhT2zdVAAAAAA==",
          "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVlB2lFrZlRbP9OGTG9YDE_Q-2yQeLxmPVFdyU&s=0",
          "name": "Actalent",
          "position": "Software Development Engineer (SDE)",
          "location": "Kirkland, WA, US",
          "date": "02/10/2024",
          "deadline": "Fri Nov 01 2024",
          "fullTime": false,
          "partTime": false,
          "contract": true,
          "remote": false,
          "onsite": true,
          "minPrice": "We reserve the right to pay above or below the posted wage based on factors unrelated to sex, race, or any other protected classification",
          "maxPrice": "Benefits are subject to change and may be subject to specific elections, plan, or program terms",
          "per": "Month",
          "description": "Software Engineer\n\nJob Description\n\nWork agnostically to deliver user stories on time and without defects. Exhibit a strong ability to quickly identify coding defects and implement automated tests to prevent regressions. Participate in code reviews of peer’s work products to provide feedback and identify defects. Track effort on ongoing tasks and update the project team in daily stand-up.\n\nHard Skills\n• Web API w/Entity Framework\n• .NET Core preferred, .NET Framework 4.6 minimum\n• Web development (React)\n• C#\n• PowerShell\n\nWork Site\n\nThis hybrid position requires some days on-site in Redmond, Washington, and some days remote.\n\nCompensation Range: $45-$55/hr\n\nWe reserve the right to pay above or below the posted wage based on factors unrelated to sex, race, or any other protected classification.\n\nRequirements\n\nEligibility requirements apply to some benefits and may depend on your job classification and length of employment. Benefits are subject to change and may be subject to specific elections, plan, or program terms. This temporary role may be eligible for the following:\n• Medical, Dental & Vision\n• 401(k)/Roth\n• Basic/Supplemental Life & AD&D\n• Short and long-term disability\n• HSA & DCFSA\n• Transportation benefits\n• Employee Assistance Program\n• Company Paid Time off or State Sick Leave\n\nAbout Actalent\n\nActalent is a global leader in engineering and sciences services and talent solutions. We help visionary companies advance their engineering and science initiatives through access to specialized experts who drive scale, innovation and speed to market. With a network of almost 30,000 consultants and more than 4,500 clients across the U.S., Canada, Asia and Europe, Actalent serves many of the Fortune 500.\n\nDiversity, Equity & Inclusion\n\nAt Actalent, Diversity And Inclusion Are a Bridge Towards The Equity And Success Of Our People. DE&I Are Embedded Into Our Culture Through\n• Hiring diverse talent\n• Maintaining an inclusive environment through persistent self-reflection\n• Building a culture of care, engagement, and recognition with clear outcomes\n• Ensuring growth opportunities for our people\n\nThe company is an equal opportunity employer and will consider all applications without regard to race, sex, age, color, religion, national origin, veteran status, disability, sexual orientation, gender identity, genetic information or any characteristic protected by law.\n\nIf you would like to request a reasonable accommodation, such as the modification or adjustment of the job application process or interviewing process due to a disability, please email actalentaccommodation@actalentservices.com for other accommodation options.",
          "requirements": "Web API w/Entity Framework\nWeb development (React)\nPowerShell",
          "responsibilities": "Work agnostically to deliver user stories on time and without defects\nExhibit a strong ability to quickly identify coding defects and implement automated tests to prevent regressions\nParticipate in code reviews of peer’s work products to provide feedback and identify defects\nTrack effort on ongoing tasks and update the project team in daily stand-up",
          "vacancy": 1,
          "apply_link": "https://www.linkedin.com/jobs/view/software-development-engineer-sde-at-actalent-4040626659?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          "availability": "Hourly",
          "education": "Graduate",
          "gender": "Not Specified",
          "age": "21+",
          "experience": "3 - 5 Years",
          "language": "English"
      },
   
      
      
      {
          "id": "QIMW1xwKzNq6Q3hDAAAAAA==",
          "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwbEyn6U1KJQ0bizexyiYzn3CiNaUOy6fYCFTe&s=0",
          "name": "Divensi",
          "position": "Net software developer",
          "location": "Redmond, WA, US",
          "date": "07/10/2024",
          "deadline": "Fri Jan 31 2025",
          "fullTime": true,
          "partTime": false,
          "contract": false,
          "remote": false,
          "onsite": true,
          "minPrice": "Unknown Salary",
          "maxPrice": "Unknown Salary",
          "per": "Month",
          "description": "Job Description\n\nJob Title : SDE / Software Development Engineer\n\nLocation : Redmond, WA\n\nDuration : 18+ months\n\nDescription :\n\nThe primary skill set required is ASP.NET, C#, SQL, Azure Webservices.\n\nAdditional Information\n\nLast updated : 2024-10-07",
          "requirements": "The primary skill set required is ASP.NET, C#, SQL, Azure Webservices",
          "responsibilities": "No responsibilities specified",
          "vacancy": 1,
          "apply_link": "https://www.talent.com/view?id=a7621b922f3e&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          "availability": "Hourly",
          "education": "Not Specified",
          "gender": "Not Specified",
          "age": "21+",
          "experience": "3 - 5 Years",
          "language": "English"
      },
      
  ]
