export { default as About } from './Aboutsection/About';
export { default as Achievement } from './Achievement/Achievement';
export { default as Dialog } from './Auth/Dialog';
// export { default as Benefit } from './Benefits/Benefit';
// export { default as BlogPage } from './BlogPage/BlogPage';
// export { default as SearchBlog } from './BlogPage/SearchBlog';
// export { default as Blogs } from './Blogsection/Blogs';
export { default as Categories } from './Categories/Categories';
export { default as ContactUs } from './ContactSlide/ContactUs';
// export { default as Download } from './Download';
export { default as FaQues } from './FaQues/FaQues';
export { default as Jobs } from './FeaturesJobs/Jobs';
export { default as Footer } from './Footer/Footer';
// export { default as GetInTouchWithUs } from './GetInTouchWithUs/GetInTouchWithUs';

export { default as Hero } from './Hero/Hero';
export { default as JobCard } from './Jobs/JobCard';
export { default as FindJob } from './Jobs/FindJob';
export { default as JobCardTwoA } from './Jobs/JobCardTwoA';
export { default as JobCartDropDown } from './Jobs/JobCartDropDown';
export { default as JobsCardOne } from './Jobs/JobsCardOne';
export { default as JobsCardTwo } from './Jobs/JobsCardTwo';
export { default as StartJourneyJob } from './Jobs/StartJourneyJob';
export { default as Navbar } from './Navbar/Navbar';
export { default as Details } from './PostJob/Details';
export { default as Post } from './PostJob/Post';
// export { default as Testimonial } from './Testimonial/Testimonial';
